server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservations_service?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
