server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/geo_location_service?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
