server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/geo_location_service?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

timofei:
  test:
    message: "Updated Welcome Message!!!"
