server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
          - "file://${config.folder.location}/common/{profile}/"
          - "file://${config.folder.location}/{application}/{profile}/"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka, http://service-registry:8080/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
  path: ./logs
  file: ${logging.path}/${spring.application.name}/${spring.application.name}.log
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
