eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka

management:
  endpoints:
    web:
      exposure:
        include:
        - "hystrix.stream"
        - "refresh"
        - "info"
        - "health"

logging:
  level:
    root: info
  path: logs
  file: ${logging.path}/${spring.application.name}/log.log
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
